version: '3.8'

services:
  backend:
    build:
      context: ./backend  # Set context to the backend folder
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app    # Map local backend folder to container /app
    # Matches the Dockerfile command + adds reload
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload